export const POST_SHORTURL_PENDING = "POST_SHORTURL_PENDING"
export const POST_SHORTURL_FAILURE = "POST_SHORTURL_FAILURE"
export const POST_SHORTURL_SUCCESS = "POST_SHORTURL_SUCCESS"

export const GET_SHORTURL_PENDING = "GET_SHORTURL_PENDING"
export const GET_SHORTURL_FAILURE = "GET_SHORTURL_FAILURE"
export const GET_SHORTURL_SUCCESS = "GET_SHORTURL_SUCCESS"

export const GET_ALLURLS_PENDING = "GET_ALLURLS_PENDING"
export const GET_ALLURLS_FAILURE = "GET_ALLURLS_FAILURE"
export const GET_ALLURLS_SUCCESS = "GET_ALLURLS_SUCCESS"

export const POST_STATS_PENDING = "POST_STATS_PENDING"
export const POST_STATS_FAILURE = "POST_STATS_FAILURE"
export const POST_STATS_SUCCESS = "POST_STATS_SUCCESS"